messages = {
    "en": {
        "hello": "Hello, <b>{}</b>.\n "
                 "By default, the Telegram interface language is set.\n"
                 "English is also installed. \n\n"
                 "Click 'Add' to add the language to Favorites,\n"
                 "Click 'Favorites' to choose the direction of translation\n\n"
                 "Command /set - allows you to set the interface language from your favorites.\n"
                 "If you don't have the language you want, add it to Favorites first, command /add",
        "add": "Select language",
        "help": "To start learning a language - just write me the words, "
                "the phrase or sentence you want to translate.\n"
                "I'll give you an answer right away!\n",
        "set": "Here you need to select the interface language from the available Favorites \n"
               "If the desired language is not available, add it to the favorites first, command /add",
        "set_answer": "now interface language - <b>{}</b>, you can change it",
        "favorites_answer": "active direction translation  <b>{} > {}</b>, you can change it",
        "delete_answer": "Select the language you want to remove in Favorites",
        "check_answer_correct": "Correct",
        "check_answer_incorrect": "Incorrect. Please try again.",

        "goodbye": "Goodbye!",
        "error": "An error occurred, please try again later.",
        # "Cancel": "",
        # "OK": "",
        # "Help": "",
        # "Tools": "",
    },
    "uk": {
        "hello": "Привіт, <b>{}</b>.\n "
                 "За замовчуванням встановлено мову інтерфейсу Telegram.\n"
                 "Англійська мова також встановлена. \n\n"
                 "Натисніть 'Add', щоб додати мову до вибраного,\n"
                 "Натисніть 'Favorites', щоб вибрати напрямок перекладу\n\n"
                 "Команда /set - дозволяє встановити мову інтерфейсу з ваших улюблених.\n"
                 "Якщо у вас немає потрібної мови, додайте її до вибраного, команда /add",
        "add": "Виберіть мову",
        "help": "Щоб почати вивчати мову - просто напишіть мені слова, "
                "фраза чи речення, які ви хочете перекласти.\n "
                "Одразу дам відповідь!\n",
        "set": "Тут вам потрібно вибрати мову інтерфейсу з доступних обраних \n"
               "Якщо потрібна мова недоступна, додайте її до вибраного, команда /add",
        "set_answer": "тепер мова інтерфейсу - <b>{}</b>, ви можете змінити її",
        "favorites_answer": "активний переклад напрямку <b>{} > {}</b>, ви можете змінити його",
        "delete_answer": "Виберіть мову, яку ви бажаєте видалити у вибраному",
        "error": "У нас халепа, зверніться до тех.підтримки.",
        "Cancel": "Скасувати",
        "OK": "Гаразд",
        "Help": "Допомога",
        "first lang": "перша мова",
        "first_lang": "перша мова"
    },
    "fr": {
        "hello": "Bonjour, comment puis-je vous aider?",
        "goodbye": "Au revoir!",
        "error": "Une erreur s'est produite, veuillez réessayer plus tard.",
    },
    "ru": {
        "hello": "Ласкаво просимо до бота для вивчення слів! Щоб почати тест, введіть /quiz. "
                 "Щоб створити картку, введіть /addflashcard. "
                 "Щоб переглянути свій прогрес, введіть /progress.",
        "goodbye": "До зустрічі!",
        "error": "У нас халепа, зверніться до тех.підтримки."
    },
}


name_lang = {
    "en": {"af": "Afrikaans", "ak": "Akan", "sq": "Albanian", "am": "Amharic", "ar": "Arabic", "hy": "Armenian", "as": "Assamese", "ay": "Aymara", "az": "Azerbaijani", "bm": "Bambara", "eu": "Basque", "be": "Belarusian", "bn": "Bengali", "bho": "Bhojpuri", "bs": "Bosnian", "bg": "Bulgarian", "ca": "Catalan", "ceb": "Cebuano", "ny": "Chichewa", "zh": "Chinese (Simplified)", "zh-CN": "Chinese (Simplified)", "zh-TW": "Chinese (Traditional)", "co": "Corsican", "hr": "Croatian", "cs": "Czech", "da": "Danish", "dv": "Divehi", "doi": "Dogri", "nl": "Dutch", "en": "English", "eo": "Esperanto", "et": "Estonian", "ee": "Ewe", "tl": "Filipino", "fi": "Finnish", "fr": "French", "fy": "Frisian", "gl": "Galician", "lg": "Ganda", "ka": "Georgian", "de": "German", "gom": "Goan Konkani", "el": "Greek", "gn": "Guarani", "gu": "Gujarati", "ht": "Haitian Creole", "ha": "Hausa", "haw": "Hawaiian", "iw": "Hebrew", "he": "Hebrew", "hi": "Hindi", "hmn": "Hmong", "hu": "Hungarian", "is": "Icelandic", "ig": "Igbo", "ilo": "Iloko", "id": "Indonesian", "ga": "Irish", "it": "Italian", "ja": "Japanese", "jw": "Javanese", "jv": "Javanese", "kn": "Kannada", "kk": "Kazakh", "km": "Khmer", "rw": "Kinyarwanda", "ko": "Korean", "kri": "Krio", "ku": "Kurdish (Kurmanji)", "ckb": "Kurdish (Sorani)", "ky": "Kyrgyz", "lo": "Lao", "la": "Latin", "lv": "Latvian", "ln": "Lingala", "lt": "Lithuanian", "lb": "Luxembourgish", "mk": "Macedonian", "mai": "Maithili", "mg": "Malagasy", "ms": "Malay", "ml": "Malayalam", "mt": "Maltese", "mni-Mtei": "Manipuri (Meitei Mayek)", "mi": "Maori", "mr": "Marathi", "lus": "Mizo", "mn": "Mongolian", "my": "Myanmar (Burmese)", "ne": "Nepali", "nso": "Northern Sotho", "no": "Norwegian", "or": "Odia (Oriya)", "om": "Oromo", "ps": "Pashto", "fa": "Persian", "pl": "Polish", "pt": "Portuguese", "pa": "Punjabi", "qu": "Quechua", "ro": "Romanian", "ru": "Russian", "sm": "Samoan", "sa": "Sanskrit", "gd": "Scots Gaelic", "sr": "Serbian", "st": "Sesotho", "sn": "Shona", "sd": "Sindhi", "si": "Sinhala", "sk": "Slovak", "sl": "Slovenian", "so": "Somali", "es": "Spanish", "su": "Sundanese", "sw": "Swahili", "sv": "Swedish", "tg": "Tajik", "ta": "Tamil", "tt": "Tatar", "te": "Telugu", "th": "Thai", "ti": "Tigrinya", "ts": "Tsonga", "tr": "Turkish", "tk": "Turkmen", "uk": "Ukrainian", "ur": "Urdu", "ug": "Uyghur", "uz": "Uzbek", "vi": "Vietnamese", "cy": "Welsh", "xh": "Xhosa", "yi": "Yiddish", "yo": "Yoruba", "zu": "Zulu"},
    "uk": {'az': 'азербайджанська', 'ay': 'аймарська', 'sq': 'албанська', 'am': 'амхарська', 'en': 'англійська', 'ar': 'арабська', 'as': 'ассамська', 'af': 'африкаанс', 'bm': 'бамбара', 'eu': 'баскська', 'bn': 'бенгальська', 'be': 'білоруська', 'my': 'бірманська', 'bg': 'болгарська', 'bs': 'боснійська', 'bho': 'бходжпурі', 'vi': 'в’єтнамська', 'cy': 'валлійська', 'hy': 'вірменська', 'haw': 'гавайська', 'ht': 'гаїтянська креольська', 'lg': 'Ганда', 'hi': 'гінді', 'el': 'грецька', 'ka': 'грузинська', 'gn': 'гуарані', 'gl': 'ґалісійська', 'gu': 'ґуджаратська', 'da': 'данська', 'doi': 'догрі', 'ee': 'еве', 'eo': 'есперанто', 'et': 'естонська', 'zu': 'зулу', 'iw': 'іврит', 'he': 'іврит', 'ig': 'ігбо (ібо)', 'yi': 'ідиш', 'ilo': 'ілоко', 'id': 'індонезійська', 'ga': 'ірландська', 'is': 'ісландська', 'es': 'іспанська', 'it': 'італійська', 'yo': 'йоруба', 'kk': 'казахська', 'km': 'камбоджійська', 'kn': 'каннада', 'ca': 'каталанська', 'qu': 'кечуа', 'ky': 'киргизька', 'zh': 'китайська (спрощена)', 'zh-CN': 'китайська (спрощена)', 'zh-TW': 'китайська (традиційна)', 'gom': 'конкані', 'ko': 'корейська', 'co': 'корсиканська', 'kri': 'кріо', 'ku': 'курдська (курманджі)', 'ckb': 'курдська (сорані)', 'xh': 'кхоса', 'lo': 'лаоська', 'la': 'латинська', 'lv': 'латиська', 'lt': 'литовська', 'ln': 'лінгала', 'lb': 'люксембурзька', 'mai': 'майтхілі', 'mk': 'македонська', 'mg': 'малагасійська', 'ms': 'малайська', 'ml': 'малаялам', 'dv': 'мальдівська', 'mt': 'мальтійська', 'mi': 'маорі', 'mr': 'маратхі', 'mni-Mtei': 'мейтейлон (маніпурі)', 'lus': 'мізо', 'mn': 'монгольська', 'ne': 'непальська', 'nl': 'нідерландська', 'de': 'німецька', 'no': 'норвезька', 'or': 'одія (орія)', 'om': 'оромо', 'pa': 'панджабська', 'fa': 'перська', 'nso': 'північна сото', 'pl': 'польська', 'pt': 'португальська', 'ps': 'пушту', 'ru': 'російська', 'rw': 'руандійська', 'ro': 'румунська', 'sm': 'самоанська', 'sa': 'санскрит', 'ceb': 'себуано', 'sr': 'сербська', 'st': 'сесото', 'si': 'сингальська', 'sd': 'сіндхі', 'sk': 'словацька', 'sl': 'словенська', 'so': 'сомалі', 'sw': 'суахілі', 'su': 'сунданська', 'tg': 'таджицька', 'th': 'тайська', 'ta': 'тамільська', 'tt': 'татарська', 'te': 'телуґу', 'ti': 'тигринcька', 'ts': 'тсонга', 'tr': 'турецька', 'tk': 'туркменська', 'hu': 'угорська', 'uz': 'узбецька', 'ug': 'уйгурська', 'uk': 'українська', 'ur': 'урду', 'tl': 'філіппінська', 'fi': 'фінська', 'fr': 'французька', 'fy': 'фризька', 'ha': 'хауса', 'hmn': 'хмонг', 'hr': 'хорватська', 'ak': 'чві', 'cs': 'чеська', 'ny': 'чичева', 'sv': 'шведська', 'sn': 'шона', 'gd': 'шотландська (ґельська)', 'jw': 'яванська', 'jv': 'яванська', 'ja': 'японська'},
    "fr": {'af': 'Afrikaans', 'sq': 'Albanais', 'de': 'Allemand', 'am': 'Amharique', 'en': 'Anglais', 'ar': 'Arabe', 'hy': 'Arménien', 'as': 'Assamais', 'ay': 'Aymara', 'az': 'Azéri', 'bm': 'Bambara', 'eu': 'Basque', 'bn': 'Bengali', 'bho': 'Bhodjpouri', 'be': 'Biélorusse', 'my': 'Birman', 'bs': 'Bosniaque', 'bg': 'Bulgare', 'ca': 'Catalan', 'ceb': 'Cebuano', 'ny': 'Chichewa', 'zh': 'Chinois (simplifié)', 'zh-CN': 'Chinois (simplifié)', 'zh-TW': 'Chinois (traditionnel)', 'si': 'Cingalais', 'ko': 'Coréen', 'co': 'Corse', 'ht': 'Créole haïtien', 'hr': 'Croate', 'da': 'Danois', 'dv': 'Divehi', 'doi': 'Dogri', 'es': 'Espagnol', 'eo': 'Espéranto', 'et': 'Estonien', 'ee': 'Ewe', 'fi': 'Finnois', 'fr': 'Français', 'fy': 'Frison', 'gd': 'Gaélique (Écosse)', 'gl': 'Galicien', 'cy': 'Gallois', 'lg': 'Ganda', 'ka': 'Géorgien', 'el': 'Grec', 'gn': 'Guarani', 'gu': 'Gujarati', 'ha': 'Haoussa', 'haw': 'Hawaïen', 'iw': 'Hébreu', 'he': 'Hébreu', 'hi': 'Hindi', 'hmn': 'Hmong', 'hu': 'Hongrois', 'ig': 'Igbo', 'ilo': 'Ilocano', 'id': 'Indonésien', 'ga': 'Irlandais', 'is': 'Islandais', 'it': 'Italien', 'ja': 'Japonais', 'jw': 'Javanais', 'jv': 'Javanais', 'kn': 'Kannada', 'kk': 'Kazakh', 'km': 'Khmer', 'rw': 'Kinyarwanda', 'ky': 'Kirghiz', 'gom': 'Konkani', 'kri': 'Krio', 'ku': 'Kurde (Kurmandji)', 'ckb': 'Kurde (Sorani)', 'lo': 'Laotien', 'la': 'Latin', 'lv': 'Letton', 'ln': 'Lingala', 'lt': 'Lituanien', 'lb': 'Luxembourgeois', 'mk': 'Macédonien', 'mai': 'Maïthili', 'ms': 'Malaisien', 'ml': 'Malayalam', 'mg': 'Malgache', 'mt': 'Maltais', 'mi': 'Maori', 'mr': 'Marathi', 'mni-Mtei': 'Meitei (Manipuri)', 'lus': 'Mizo', 'mn': 'Mongol', 'nl': 'Néerlandais', 'ne': 'Népalais', 'no': 'Norvégien', 'or': 'Odia (Oriya)', 'om': 'Oromo', 'ug': 'Ouïgour', 'uz': 'Ouzbek', 'ps': 'Pachtô', 'pa': 'Panjabi', 'fa': 'Persan', 'tl': 'Philippin', 'pl': 'Polonais', 'pt': 'Portugais', 'qu': 'Quechua', 'ro': 'Roumain', 'ru': 'Russe', 'sm': 'Samoan', 'sa': 'Sanscrit', 'sr': 'Serbe', 'st': 'Sesotho', 'sn': 'Shona', 'sd': 'Sindhî', 'sk': 'Slovaque', 'sl': 'Slovène', 'so': 'Somali', 'nso': 'Sotho du Nord', 'su': 'Soundanais', 'sv': 'Suédois', 'sw': 'Swahili', 'tg': 'Tadjik', 'ta': 'Tamoul', 'tt': 'Tatar', 'cs': 'Tchèque', 'te': 'Telugu', 'th': 'Thaï', 'ti': 'Tigrigna', 'ts': 'Tsonga', 'tr': 'Turc', 'tk': 'Turkmène', 'ak': 'Twi', 'uk': 'Ukrainien', 'ur': 'Urdu', 'vi': 'Vietnamien', 'xh': 'Xhosa', 'yi': 'Yiddish', 'yo': 'Yorouba', 'zu': 'Zoulou'},
    "ru": {'az': 'азербайджанский', 'ay': 'аймара', 'sq': 'албанский', 'am': 'амхарский', 'en': 'английский', 'ar': 'арабский', 'hy': 'армянский', 'as': 'ассамский', 'af': 'африкаанс', 'bm': 'бамбара', 'eu': 'баскский', 'be': 'белорусский', 'bn': 'бенгальский', 'my': 'бирманский', 'bg': 'болгарский', 'bs': 'боснийский', 'bho': 'бходжпури', 'cy': 'валлийский', 'hu': 'венгерский', 'vi': 'вьетнамский', 'haw': 'гавайский', 'gl': 'галисийский', 'lg': 'ганда', 'el': 'греческий', 'ka': 'грузинский', 'gn': 'гуарани', 'gu': 'гуджарати', 'da': 'датский', 'doi': 'догри', 'zu': 'зулу', 'iw': 'иврит', 'he': 'иврит', 'ig': 'игбо', 'yi': 'идиш', 'ilo': 'илоканский', 'id': 'индонезийский', 'ga': 'ирландский', 'is': 'исландский', 'es': 'испанский', 'it': 'итальянский', 'yo': 'йоруба', 'kk': 'казахский', 'kn': 'каннада', 'ca': 'каталанский', 'qu': 'кечуа', 'ky': 'киргизский', 'zh-TW': 'китайский (традиционный)', 'zh': 'китайский (упрощенный)', 'zh-CN': 'китайский (упрощенный)', 'gom': 'конкани', 'ko': 'корейский', 'co': 'корсиканский', 'xh': 'коса', 'ht': 'креольский (гаити)', 'kri': 'крио', 'ku': 'курдский (курманджи)', 'ckb': 'курдский (сорани)', 'km': 'кхмерский', 'lo': 'лаосский', 'la': 'латинский', 'lv': 'латышский', 'ln': 'лингала', 'lt': 'литовский', 'lb': 'люксембургский', 'mai': 'майтхили', 'mk': 'македонский', 'mg': 'малагасийский', 'ms': 'малайский', 'ml': 'малаялам', 'dv': 'мальдивский', 'mt': 'мальтийский', 'mi': 'маори', 'mr': 'маратхи', 'mni-Mtei': 'мейтейлон (манипури)', 'lus': 'мизо', 'mn': 'монгольский', 'de': 'немецкий', 'ne': 'непальский', 'nl': 'нидерландский', 'no': 'норвежский', 'or': 'ория', 'om': 'оромо', 'pa': 'панджаби', 'fa': 'персидский', 'pl': 'польский', 'pt': 'португальский', 'ps': 'пушту', 'rw': 'руанда', 'ro': 'румынский', 'ru': 'русский', 'sm': 'самоанский', 'sa': 'санскрит', 'ceb': 'себуанский', 'nso': 'северный сото', 'sr': 'сербский', 'st': 'сесото', 'si': 'сингальский', 'sd': 'синдхи', 'sk': 'словацкий', 'sl': 'словенский', 'so': 'сомалийский', 'sw': 'суахили', 'su': 'сунданский', 'tg': 'таджикский', 'th': 'тайский', 'ta': 'тамильский', 'tt': 'татарский', 'te': 'телугу', 'ti': 'тигринья', 'ts': 'тсонга', 'tr': 'турецкий', 'tk': 'туркменский', 'uz': 'узбекский', 'ug': 'уйгурский', 'uk': 'украинский', 'ur': 'урду', 'tl': 'филиппинский', 'fi': 'финский', 'fr': 'французский', 'fy': 'фризский', 'ha': 'хауса', 'hi': 'хинди', 'hmn': 'хмонг', 'hr': 'хорватский', 'ak': 'чви', 'ny': 'чева', 'cs': 'чешский', 'sv': 'шведский', 'sn': 'шона', 'gd': 'шотландский (гэльский)', 'ee': 'эве', 'eo': 'эсперанто', 'et': 'эстонский', 'jw': 'яванский', 'jv': 'яванский', 'ja': 'японский'},
    "de": {'af': 'Afrikaans', 'sq': 'Albanisch', 'am': 'Amharisch', 'ar': 'Arabisch', 'hy': 'Armenisch', 'az': 'Aserbaidschanisch', 'as': 'Assamesisch', 'ay': 'Aymara', 'bm': 'Bambara', 'eu': 'Baskisch', 'be': 'Belarussisch', 'bn': 'Bengalisch', 'bho': 'Bhojpuri', 'my': 'Birmanisch', 'bs': 'Bosnisch', 'bg': 'Bulgarisch', 'ceb': 'Cebuano', 'ny': 'Chichewa', 'zh-TW': 'Chinesisch (traditionell)', 'zh': 'Chinesisch (vereinfacht)', 'zh-CN': 'Chinesisch (vereinfacht)', 'da': 'Dänisch', 'de': 'Deutsch', 'dv': 'Dhivehi', 'doi': 'Dogri', 'en': 'Englisch', 'eo': 'Esperanto', 'et': 'Estnisch', 'ee': 'Ewe', 'tl': 'Filipino', 'fi': 'Finnisch', 'fr': 'Französisch', 'fy': 'Friesisch', 'gl': 'Galizisch', 'ka': 'Georgisch', 'el': 'Griechisch', 'gn': 'Guarani', 'gu': 'Gujarati', 'ht': 'Haitianisch', 'ha': 'Hausa', 'haw': 'Hawaiisch', 'iw': 'Hebräisch', 'he': 'Hebräisch', 'hi': 'Hindi', 'hmn': 'Hmong', 'ig': 'Igbo', 'ilo': 'Ilokano', 'id': 'Indonesisch', 'ga': 'Irisch', 'is': 'Isländisch', 'it': 'Italienisch', 'ja': 'Japanisch', 'jw': 'Javanisch', 'jv': 'Javanisch', 'yi': 'Jiddisch', 'kn': 'Kannada', 'kk': 'Kasachisch', 'ca': 'Katalanisch', 'km': 'Khmer', 'rw': 'Kinyarwanda', 'ky': 'Kirgisisch', 'gom': 'Konkani', 'ko': 'Koreanisch', 'co': 'Korsisch', 'kri': 'Krio', 'hr': 'Kroatisch', 'ku': 'Kurdisch (Kurmandschi)', 'ckb': 'Kurdisch (Sorani)', 'lo': 'Lao', 'la': 'Latein', 'lv': 'Lettisch', 'ln': 'Lingala', 'lt': 'Litauisch', 'lg': 'Luganda', 'lb': 'Luxemburgisch', 'mai': 'Maithili', 'mg': 'Malagasy', 'ml': 'Malayalam', 'ms': 'Malaysisch', 'mt': 'Maltesisch', 'mi': 'Maori', 'mr': 'Marathi', 'mk': 'Mazedonisch', 'mni-Mtei': 'Meitei (Manipuri)', 'lus': 'Mizo', 'mn': 'Mongolisch', 'ne': 'Nepalesisch', 'nl': 'Niederländisch', 'nso': 'Nord-Sotho', 'no': 'Norwegisch', 'or': 'Odia (Oriya)', 'om': 'Oromo', 'ps': 'Paschtu', 'fa': 'Persisch', 'pl': 'Polnisch', 'pt': 'Portugiesisch', 'pa': 'Punjabi', 'qu': 'Quechua', 'ro': 'Rumänisch', 'ru': 'Russisch', 'sm': 'Samoanisch', 'sa': 'Sanskrit', 'gd': 'Schottisch-Gälisch', 'sv': 'Schwedisch', 'sr': 'Serbisch', 'st': 'Sesotho', 'sn': 'Shona', 'sd': 'Sindhi', 'si': 'Singhalesisch', 'sk': 'Slowakisch', 'sl': 'Slowenisch', 'so': 'Somali', 'es': 'Spanisch', 'su': 'Sundanesisch', 'sw': 'Swahili', 'tg': 'Tadschikisch', 'ta': 'Tamil', 'tt': 'Tatarisch', 'te': 'Telugu', 'th': 'Thailändisch', 'ti': 'Tigrinya', 'cs': 'Tschechisch', 'ts': 'Tsonga', 'tr': 'Türkisch', 'tk': 'Turkmenisch', 'ak': 'Twi', 'ug': 'Uigurisch', 'uk': 'Ukrainisch', 'hu': 'Ungarisch', 'ur': 'Urdu', 'uz': 'Usbekisch', 'vi': 'Vietnamesisch', 'cy': 'Walisisch', 'xh': 'Xhosa', 'yo': 'Yoruba', 'zu': 'Zulu'},
}

